# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  _extends: .github:.github/settings.yml

  # The name of the repository. Changing this will rename the repository
  name: test-repository-1

  # A short description of the repository that will show up on GitHub
  description: some repo

  # A URL with more information about the repository
  homepage: https://example.github.io/test-repository-1-2
